# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-07 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_saas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypageabout',
            name='features_header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypageabout',
            name='features_image',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypageabout',
            name='features_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypageaboutsteps',
            name='step_details',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypageaboutsteps',
            name='step_header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypagecontent',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypagefeature',
            name='feature_details',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypagefeature',
            name='feature_header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypagefeature',
            name='feature_image',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypagelanding',
            name='footer_facebook',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypagelanding',
            name='footer_instagram',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypagelanding',
            name='footer_logo',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypagelanding',
            name='footer_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypagelanding',
            name='footer_twitter',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypagelanding',
            name='footer_youtube',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypagelanding',
            name='header_logo',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypagelanding',
            name='landing_header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypagelanding',
            name='landing_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypageloggedin',
            name='footer_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypageloggedin',
            name='support_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypagepricing',
            name='pricing_details',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypagepricing',
            name='pricing_header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companypagesignup',
            name='terms_text',
            field=models.CharField(max_length=100),
        ),
    ]
