# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-07 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_saas', '0002_auto_20180907_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypagelanding',
            name='landing_image',
            field=models.URLField(default='AAAA', max_length=100),
            preserve_default=False,
        ),
    ]
