# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-04 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_saas', '0005_auto_20181004_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypageabout',
            name='features_header',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companypageabout',
            name='features_image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companypageabout',
            name='features_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companypageaboutsteps',
            name='step_details',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companypageaboutsteps',
            name='step_header',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companypagefeature',
            name='feature_details',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companypagefeature',
            name='feature_header',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companypagefeature',
            name='feature_image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companypageloggedin',
            name='footer_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companypageloggedin',
            name='support_email',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companypagepricing',
            name='pricing_details',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companypagepricing',
            name='pricing_header',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companypagesignup',
            name='terms_text',
            field=models.CharField(max_length=500),
        ),
    ]
