# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-04 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('va_saas', '0006_auto_20181004_1010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyPageContent',
            new_name='CompanyPage',
        ),
        migrations.AddField(
            model_name='companypagepricing',
            name='company_page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='va_saas.CompanyPage'),
        ),
    ]
