# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-26 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0048_auto_20180905_1002'),
        ('va_saas', '0007_auto_20181004_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPlanFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_image', models.ImageField(upload_to=b'')),
                ('plan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='silver.Plan')),
            ],
        ),
    ]
