# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-26 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_saas', '0008_companyplanfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyplanfeatures',
            name='plan_description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
