# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-30 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('va_saas', '0009_companyplanfeatures_plan_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyplanfeatures',
            name='plan',
        ),
        migrations.DeleteModel(
            name='CompanyPlanFeatures',
        ),
    ]
