# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-30 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('silver', '0048_auto_20180905_1002'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_image', models.ImageField(upload_to=b'')),
                ('plan_description', models.CharField(max_length=200)),
                ('plan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='silver.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_input_type', models.CharField(max_length=20)),
                ('step_value', models.CharField(max_length=30)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silver_extensions.PlanFeatures')),
            ],
        ),
        migrations.CreateModel(
            name='UserCustomerMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('partner', 'Partner'), ('it_admin', 'IT Admin'), ('owner', 'Owner')], max_length=7)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silver.Customer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
